<a href="https://colab.research.google.com/github/yfhkucing/regression_bms/blob/master/Model_revisi_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
feature = pd.read_excel('/content/input_big_4.xlsx',sheet_name='Sheet2')
label = pd.read_excel('/content/data_big_4.xlsx', sheet_name='Sheet2')

In [3]:
i=0
x=feature[i::i+30]

In [ ]:
i=0
label[i:i+30]

In [37]:
y=[]
y1=[]
f=0
for i in range(192):
  b = label[f:f+15]
  c = label[f+15:f+30]
  b = b.drop(['koor_x','koor_y'],axis=1)
  c = c.drop(['koor_x','koor_y'],axis=1)
  y.append(b)
  y1.append(c)
  f+=30

In [38]:
y_1=[]
y_2=[]
for i in range(192):
  y[i]=y[i].drop(['Vx','Vy'],axis=1)
  y1[i]=y1[i].drop(['Vx','Vy'],axis=1)
  y_1.append(y[i].to_numpy().flatten())
  y_2.append(y1[i].to_numpy().flatten())

In [42]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y_1, test_size=0.25, random_state= 10)

In [43]:
x_train

,Jendela_1,Jendela_2,Jendela_3,Jendela_4,Jendela_5,Jendela_6,Jendela_7,Jendela_8,Jendela_9,AC,...,Fan i/3,Fan i/4,Fan i/5,Fan i/6,Fan o/1,Fan o/2,Fan o/3,Fan o/4,Fan o/5,Fan o/6
4080,1,1,1,1,1,1,1,1,1,0,...,1,1,1,1,1,1,1,1,1,1
630,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,1,0,0
1650,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3090,1,1,1,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
2070,0,0,0,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3390,1,1,1,1,1,1,1,1,1,0,...,0,1,0,0,1,0,0,1,0,0
1920,0,0,0,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
450,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,1,0,0
3750,1,1,1,1,1,1,1,1,1,0,...,1,1,1,0,1,1,1,1,1,0
270,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [47]:
len(y_train)

144